// flow-typed signature: b24937c275d98f6ff4a1763bfb90098c
// flow-typed version: <<STUB>>/react-swipeable-views-native_v^0.11.1/flow_v0.41.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-swipeable-views-native'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-swipeable-views-native' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-swipeable-views-native/lib/index' {
  declare module.exports: any;
}

declare module 'react-swipeable-views-native/lib/SwipeableViews.animated' {
  declare module.exports: any;
}

declare module 'react-swipeable-views-native/lib/SwipeableViews.scroll' {
  declare module.exports: any;
}

declare module 'react-swipeable-views-native/src/index' {
  declare module.exports: any;
}

declare module 'react-swipeable-views-native/src/SwipeableViews.animated' {
  declare module.exports: any;
}

declare module 'react-swipeable-views-native/src/SwipeableViews.scroll' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-swipeable-views-native/lib/index.js' {
  declare module.exports: $Exports<'react-swipeable-views-native/lib/index'>;
}
declare module 'react-swipeable-views-native/lib/SwipeableViews.animated.js' {
  declare module.exports: $Exports<'react-swipeable-views-native/lib/SwipeableViews.animated'>;
}
declare module 'react-swipeable-views-native/lib/SwipeableViews.scroll.js' {
  declare module.exports: $Exports<'react-swipeable-views-native/lib/SwipeableViews.scroll'>;
}
declare module 'react-swipeable-views-native/src/index.js' {
  declare module.exports: $Exports<'react-swipeable-views-native/src/index'>;
}
declare module 'react-swipeable-views-native/src/SwipeableViews.animated.js' {
  declare module.exports: $Exports<'react-swipeable-views-native/src/SwipeableViews.animated'>;
}
declare module 'react-swipeable-views-native/src/SwipeableViews.scroll.js' {
  declare module.exports: $Exports<'react-swipeable-views-native/src/SwipeableViews.scroll'>;
}
